"""Remove projects feature: drop project_id columns and projects table.

Revision ID: 0003_remove_projects
Revises: 0002_add_property_detail_fields
Create Date: 2026-09-23

Elimina la funcionalidad Proyectos (tabla ``projects`` y FKs
``properties.project_id``, ``documents.project_id`` y columna
``document_chunks.project_id``). El historial anterior se conserva
intacto; esta migración de limpieza es el único cambio de schema.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0003_remove_projects"
down_revision: str = "0002_add_property_detail_fields"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Drop FK constraints if they exist (names are autogenerated in the
    # initial migration, so use IF EXISTS via raw SQL for robustness).
    op.execute(
        "ALTER TABLE properties DROP CONSTRAINT IF EXISTS "
        "properties_project_id_fkey"
    )
    op.execute(
        "ALTER TABLE documents DROP CONSTRAINT IF EXISTS "
        "documents_project_id_fkey"
    )
    # Drop columns (idempotent).
    op.execute("ALTER TABLE properties DROP COLUMN IF EXISTS project_id")
    op.execute("ALTER TABLE documents DROP COLUMN IF EXISTS project_id")
    op.execute("ALTER TABLE document_chunks DROP COLUMN IF EXISTS project_id")
    # Drop the projects table itself.
    op.execute("DROP TABLE IF EXISTS projects")


def downgrade() -> None:
    # Re-create the projects table and FK columns exactly as in the
    # initial schema (nullable, no data restored).
    import sqlalchemy as sa

    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.execute("ALTER TABLE properties ADD COLUMN IF NOT EXISTS project_id UUID")
    op.execute(
        "ALTER TABLE properties ADD CONSTRAINT properties_project_id_fkey "
        "FOREIGN KEY (project_id) REFERENCES projects(id)"
    )
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS project_id UUID")
    op.execute(
        "ALTER TABLE documents ADD CONSTRAINT documents_project_id_fkey "
        "FOREIGN KEY (project_id) REFERENCES projects(id)"
    )
    op.execute(
        "ALTER TABLE document_chunks ADD COLUMN IF NOT EXISTS project_id UUID"
    )
