"""add email to lead

Revision ID: 135e50c95152
Revises: 2cb1208d4d83
Create Date: 2026-09-20 23:29:02.596005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '135e50c95152'
down_revision: Union[str, None] = '2cb1208d4d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('email', sa.String(length=160), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'email')
    # ### end Alembic commands ###
