"""widen_ai_events_status_to_64_chars

Revision ID: 2cb1208d4d83
Revises: feeb75f8794e
Create Date: 2026-09-19 20:03:25.845774

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2cb1208d4d83'
down_revision: str | None = 'dbd22e5c5ba6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_events', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
