"""add alert system: extend saved_searches, add notification_history

Revision ID: 3091cc588037
Revises: 135e50c95152
Create Date: 2026-09-21 17:41:52.823749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3091cc588037'
down_revision: Union[str, None] = '135e50c95152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
