"""add alert system: extend saved_searches, add notification_history

Revision ID: 55d8459dd9e7
Revises: 3091cc588037
Create Date: 2026-09-21 17:43:22.224039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '55d8459dd9e7'
down_revision: Union[str, None] = '3091cc588037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saved_search_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False, server_default='telegram'),
    sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_search_id', 'property_id', name='uq_alert_property')
    )
    op.create_index('ix_notification_history_search', 'notification_history', ['saved_search_id'], unique=False)
    op.create_index('ix_notification_history_property', 'notification_history', ['property_id'], unique=False)
    op.add_column('saved_searches', sa.Column('telegram_user_id', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('saved_searches', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('saved_searches', sa.Column('user_name', sa.String(length=160), nullable=False, server_default=''))
    op.add_column('saved_searches', sa.Column('status', sa.Enum('active', 'paused', 'cancelled', name='alertstatus', native_enum=False, length=32), nullable=False, server_default='active'))
    op.add_column('saved_searches', sa.Column('frequency_hours', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('saved_searches', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('saved_searches', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_saved_searches_status'), 'saved_searches', ['status'], unique=False)
    op.drop_column('saved_searches', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_searches', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_saved_searches_status'), table_name='saved_searches')
    op.drop_column('saved_searches', 'updated_at')
    op.drop_column('saved_searches', 'last_checked_at')
    op.drop_column('saved_searches', 'frequency_hours')
    op.drop_column('saved_searches', 'status')
    op.drop_column('saved_searches', 'user_name')
    op.drop_column('saved_searches', 'telegram_chat_id')
    op.drop_column('saved_searches', 'telegram_user_id')
    op.drop_index('ix_notification_history_search', table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_saved_search_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_property_id'), table_name='notification_history')
    op.drop_index('ix_notification_history_property', table_name='notification_history')
    op.drop_table('notification_history')
    # ### end Alembic commands ###
