"""migrate embeddings to halfvec 2048 for nemotron-3-embed-1b

Revision ID: b976e4404b71
Revises: 8027eadf0d90
Create Date: 2026-09-16 17:47:58.402225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector
import pgvector.sqlalchemy.halfvec


revision: str = 'b976e4404b71'
down_revision: Union[str, None] = '8027eadf0d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_embedding', table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.execute("ALTER TABLE document_chunks ALTER COLUMN embedding TYPE halfvec(2048) USING NULL")
    op.drop_index('ix_properties_title_embedding', table_name='properties', postgresql_ops={'title_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.execute("ALTER TABLE properties ALTER COLUMN title_embedding TYPE halfvec(2048) USING NULL")
    op.create_index('ix_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_properties_title_embedding', 'properties', ['title_embedding'], unique=False, postgresql_ops={'title_embedding': 'halfvec_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_properties_title_embedding', 'properties', ['title_embedding'], unique=False, postgresql_ops={'title_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('properties', 'title_embedding',
               existing_type=pgvector.sqlalchemy.halfvec.HALFVEC(dim=2048),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               existing_nullable=True)
    op.create_index('ix_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.halfvec.HALFVEC(dim=2048),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=256),
               existing_nullable=True)
    # ### end Alembic commands ###
